export type SoldConditionBucket = "new_sealed" | "used" | "unknown";

export type SoldHistoryRecord = {
  conditionBucket: SoldConditionBucket;
  currency?: string;
  customLabel?: string;
  ebayAdFees?: number;
  ebaySaleFeeCredits?: number;
  ebaySaleFees?: number;
  ebaySaleFeesGross?: number;
  economicsAttribution?: Record<string, string>;
  estimatedNetAfterEbayCosts?: number;
  financialRefundAmount?: number;
  fulfillmentRefundAmount?: number;
  inferredArtist?: string;
  inferredReleaseTitle?: string;
  itemNumber?: string;
  lineItemId?: string;
  mediaGrade?: string;
  normalizedKey: string;
  otherEbayCharges?: number;
  orderNumber?: string;
  quantity: number;
  recordKey?: string;
  refundRate?: number;
  refundAmount?: number;
  retainedQuantity?: number;
  saleDate?: string;
  shippingLabelCost?: number;
  shippingLabelCredits?: number;
  shippingLabelDebits?: number;
  shippingPaid: number;
  sku?: string;
  sleeveGrade?: string;
  soldFor: number;
  sourceSheet: string;
  title: string;
  totalBuyerPaid: number;
};

export type SoldHistoryComp = {
  averageShipping: number;
  averageSoldFor: number;
  averageTotal: number;
  conditionMetrics: Record<SoldConditionBucket, SoldHistoryConditionMetrics>;
  conditionCounts: Record<SoldConditionBucket, number>;
  conditionTransactionCounts: Record<SoldConditionBucket, number>;
  conservativeResalePrice: number;
  count: number;
  daysSinceLastSale: number | null;
  evidenceScope: "single-account-own-sales";
  exampleTitles: string[];
  fullyRefundedTransactionCount: number;
  fullyRefundedUnits: number;
  grossTransactionCount: number;
  grossUnits: number;
  inferredArtist?: string;
  inferredReleaseTitle?: string;
  latestSaleDate?: string;
  maxTotal: number;
  medianTotal: number;
  minTotal: number;
  normalizedKey: string;
  oneSellerSoldCount: null;
  priceP25: number;
  records: SoldHistoryRecord[];
  refundRate: number;
  salesPerMonth90Days: number;
  sellerCountEvidence: null;
  supportsMarketplaceSellerRepeatProof: false;
  transactionCount: number;
  unitsSold: number;
  unitsSold30Days: number;
  unitsSold90Days: number;
  unitsSold365Days: number;
};

export type SoldHistoryConditionMetrics = {
  averageShipping: number;
  averageSoldFor: number;
  averageTotal: number;
  averageTotal30Days: number;
  averageTotal90Days: number;
  averageTotal365Days: number;
  conservativeResalePrice: number;
  daysSinceLastSale: number | null;
  fullyRefundedTransactionCount: number;
  fullyRefundedUnits: number;
  grossTransactionCount: number;
  grossUnits: number;
  latestSaleDate?: string;
  maxTotal: number;
  medianTotal: number;
  medianTotal30Days: number;
  medianTotal90Days: number;
  medianTotal365Days: number;
  minTotal: number;
  priceP25: number;
  priceP25_30Days: number;
  priceP25_90Days: number;
  priceP25_365Days: number;
  refundRate: number;
  salesPerMonth90Days: number;
  transactionCount: number;
  unitsSold: number;
  unitsSold30Days: number;
  unitsSold90Days: number;
  unitsSold365Days: number;
};

export type SoldHistoryIndex = {
  artistAggregates?: SoldHistoryArtistAggregate[];
  comps: SoldHistoryComp[];
  createdAt: string;
  fullyRefundedUnitCount: number;
  grossUnitCount: number;
  recordCount: number;
  snapshotDate: string;
  source: string;
  sourceSheets: string[];
  unitCount: number;
  version: 2;
};

export type SoldHistoryArtistAggregate = {
  artist: string;
  averageTotal: number;
  conditionCounts: Record<SoldConditionBucket, number>;
  distinctReleaseCount: number;
  latestSaleDate?: string;
  medianTotal: number;
  normalizedArtist: string;
  salesPerMonth90Days: number;
  transactionCount: number;
  unitsSold: number;
  unitsSold30Days: number;
  unitsSold90Days: number;
  unitsSold365Days: number;
};

export type SoldHistorySearchResult = {
  matchScore: number;
  comp: SoldHistoryComp;
};
