import type { VinylShopSource } from "./vinylShopSources";

export type ArbitrageDecision = "BUY" | "WATCH" | "REVIEW" | "REJECT";
export type ArbitrageOpportunityType = "product_deal" | "sitewide_sale";
export type ArbitrageMatchConfidence = "high" | "medium" | "low" | "unknown";
export type ArbitrageSoldCondition = "new_sealed" | "used" | "unknown";
export type ArbitragePriorityBand = "A" | "B" | "C" | "REJECT";
export type ArbitrageStrategyId = "balanced" | "fast_turn" | "high_margin";
export type ArbitrageUserPreference = "avoid" | "neutral" | "prefer";

export type ArbitrageStrategyOption = {
  demandSupport: "partial" | "qualified" | "unsupported";
  demandQualified: boolean;
  economicsQualified: boolean;
  eligible: boolean;
  estimatedDaysToSell: number | null;
  id: ArbitrageStrategyId;
  label: string;
  maxDaysToSell: number;
  minNetProfitDollars: number;
  minRoiRatio: number;
  netProfitGapDollars: number | null;
  reason: string;
  roiGapRatio: number | null;
  thresholdReasons: string[];
  watchQualified: boolean;
};

export type ArbitragePriorityBreakdown = {
  competitionAndSupply: number;
  demandDurability: number;
  economics: number;
  evergreenPrior: number;
  evidenceQuality: number;
};

export type ArbitrageCostInputs = {
  duty?: number | null;
  fxFees?: number | null;
  inboundShipping?: number | null;
  marketplaceFeeFixed?: number | null;
  marketplaceFeeRate?: number | null;
  otherAcquisitionCosts?: number | null;
  otherSellingCosts?: number | null;
  outboundShipping?: number | null;
  packaging?: number | null;
  promotedListingRate?: number | null;
  returnsReserveAmount?: number | null;
  returnsReserveRate?: number | null;
  taxAmount?: number | null;
  taxRatePercent?: number | null;
};

export type ArbitrageCostLedger = {
  duty: number;
  expectedNetProfit: number | null;
  expectedResalePrice: number | null;
  fxFees: number;
  inboundShipping: number;
  landedCost: number;
  marketplaceFee: number;
  marketplaceFeeFixed: number;
  marketplaceFeeRate: number;
  marginRatio: number | null;
  otherAcquisitionCosts: number;
  otherSellingCosts: number;
  outboundShipping: number;
  packaging: number;
  promotedListingFee: number;
  promotedListingRate: number;
  purchasePrice: number;
  returnsReserve: number;
  returnsReserveRate: number;
  roiRatio: number | null;
  salesTax: number;
  sellingCosts: number;
  totalCost: number;
};

export type ArbitrageSoldEvidence = {
  artistMatchConfirmed?: boolean;
  artistMismatchReasons?: string[];
  capturedAt?: string | null;
  condition?: ArbitrageSoldCondition;
  conservativeResalePrice?: number | null;
  daysSinceLastSale?: number | null;
  editionMatchConfirmed?: boolean;
  editionMismatchReasons?: string[];
  latestSaleDate?: string | null;
  matchConfidence?: ArbitrageMatchConfidence | number | null;
  priceP25?: number | null;
  salesPerMonth?: number | null;
  source?: string;
  status?: "candidate" | "failed" | "no_rows" | "pending" | "validated";
  supportsMarketplaceSellerRepeatProof?: boolean;
  transactionCount?: number | null;
  unitsSold30Days?: number | null;
  unitsSold90Days?: number | null;
  unitsSold365Days?: number | null;
  unitsSold1095Days?: number | null;
  velocityEvidence?: "aggregate_last_sale_only" | "dated_transactions" | "unknown";
};

export type ArbitrageActiveEvidence = {
  capturedAt?: string | null;
  exactMatchedListingCount?: number | null;
  matchConfidence?: ArbitrageMatchConfidence | number | null;
  rawListingsInspected?: number | null;
  searchComplete?: boolean;
  status?: "available" | "failed" | "no_results";
};

export type ArbitrageSettings = {
  defaultDuty: number;
  defaultFxFees: number;
  defaultInboundShipping: number;
  defaultMarketplaceFeeFixed: number;
  defaultMarketplaceFeeRate: number;
  defaultOtherAcquisitionCosts: number;
  defaultOtherSellingCosts: number;
  defaultOutboundShipping: number;
  defaultPackaging: number;
  defaultPromotedListingRate: number;
  defaultReturnsReserveAmount: number;
  defaultReturnsReserveRate: number;
  balancedMaxDaysToSell: number;
  balancedMinNetProfitDollars: number;
  balancedMinRoiRatio: number;
  fastTurnMaxDaysToSell: number;
  fastTurnMinNetProfitDollars: number;
  fastTurnMinRoiRatio: number;
  highMarginMaxDaysToSell: number;
  highMarginMinNetProfitDollars: number;
  highMarginMinRoiRatio: number;
  maxActiveListings: number;
  maxActiveListingsForScarceSingle: number;
  maxActiveSupplyMonths: number;
  maxDaysSinceLastSale: number;
  maxEvidenceAgeDays: number;
  maxOfferAgeDays: number;
  minAverageSoldPrice: number;
  minBuyMatchConfidence: number;
  minMarginDollars: number;
  minMarginRatio: number;
  minNetProfitDollars: number;
  minOneSellerSoldCount: number;
  minRoiRatio: number;
  minSalesPerMonth: number;
  minSellThroughRate: number;
  minSoldUnits90Days: number;
  minTotalSoldCount: number;
  minPriorityScoreForBuy: number;
  minPriorityScoreForTest: number;
  sourceTaxRatePercent: number;
  watchMinNetProfitDollars: number;
  watchMinRoiRatio: number;
};

export type ArbitrageFind = {
  activeEvidence?: ArbitrageActiveEvidence;
  activeListingCount?: number | null;
  activeListingCountIsExactMatch?: boolean;
  appliedSaleCampaignId?: string | null;
  appliedSaleCode?: string | null;
  appliedSaleDiscountPercent?: number | null;
  appliedSaleEvidence?: string | null;
  appliedSaleScope?: string | null;
  appliedSaleUrl?: string | null;
  artist: string;
  artistSoldUnits365Days?: number | null;
  artistSoldUnits1095Days?: number | null;
  externalEvergreenScore?: number | null;
  userEvergreenPreference?: ArbitrageUserPreference;
  averageSoldPrice?: number | null;
  averageSoldShipping?: number | null;
  barcode?: string | null;
  capturedAt: string;
  condition?: string;
  conservativeResalePrice?: number | null;
  costs?: ArbitrageCostInputs;
  currencyConversionRate?: number | null;
  currencyConversionUpdatedAt?: string | null;
  daysSinceLastSale?: number | null;
  dismissedAt?: string;
  discoveryUrl?: string | null;
  ebayActiveEditionIdentity?: {
    colors?: string[];
    format?: string | null;
    key?: string;
    retailerExclusive?: string | null;
    signals?: string[];
  };
  ebayResearchKeyword?: string;
  ebayResearchKeywordVariants?: string[];
  ebayResearchLatestSaleDate?: string | null;
  ebayResearchRows?: Array<{
    avgShipping?: number | null;
    avgSoldPrice?: number | null;
    dateLastSold?: string | null;
    itemSales?: number | null;
    title: string;
    totalSold: number;
  }>;
  ebayResearchStatus?: "failed" | "no_rows" | "pending" | "validated";
  ebayResearchUpdatedAt?: string;
  ebayResearchUrl?: string;
  ebaySoldCondition?: ArbitrageSoldCondition;
  ebaySoldMatchConfidence?: ArbitrageMatchConfidence | number | null;
  ebayActiveListings?: Array<{
    condition?: string;
    currency?: string;
    editionSignals?: string[];
    id?: string;
    itemUrl?: string;
    matchConfidence?: ArbitrageMatchConfidence;
    matchScore?: number;
    matchedVariant?: string;
    price: number;
    shippingPrice: number;
    title: string;
    totalPrice: number;
  }>;
  ebayActiveSearchError?: string;
  ebayActiveSearchKeyword?: string;
  ebayActiveSearchStatus?: "available" | "failed" | "no_results";
  ebayActiveSearchUpdatedAt?: string;
  ebayActiveSearchUrl?: string;
  ebayActiveSearchVariants?: string[];
  ebayActiveMatchConfidence?: ArbitrageMatchConfidence | number | null;
  ebayActiveRawListingsInspected?: number | null;
  ebayActiveSearchComplete?: boolean;
  exactActiveListingCount?: number | null;
  id: string;
  lowestActiveItemPrice?: number | null;
  lowestActivePrice?: number | null;
  lowestActiveShippingPrice?: number | null;
  lowestActiveTitle?: string;
  lowestActiveUrl?: string;
  latestSoldDate?: string | null;
  listPrice?: number | null;
  longTermSalesPerMonth?: number | null;
  longTermSupplyMonths?: number | null;
  notes?: string[];
  oneSellerSoldCount?: number | null;
  opportunityType?: ArbitrageOpportunityType;
  productResearchRows?: Array<{
    avgShipping?: number | null;
    avgSoldPrice?: number | null;
    dateLastSold?: string | null;
    itemSales?: number | null;
    title: string;
    totalSold: number;
  }>;
  purchasePrice: number;
  purchasePriceIncludesShipping?: boolean;
  purchaseOfferVerification?: "campaign_advertised" | "direct_retailer" | "discovery_lead" | "official_api";
  purchaseRetailerDomain?: string;
  purchaseRetailerName?: string;
  purchasePriceUsd?: number | null;
  quantityAvailable?: number | null;
  retailerBadges?: string[];
  retailerBestSeller?: boolean;
  retailerCustomerPick?: boolean;
  retailerRating?: number | null;
  retailerReviewCount?: number | null;
  retailerSellerName?: string | null;
  retailerSoldBySource?: boolean | null;
  endedAt?: string | null;
  lastSeenAt?: string;
  saleScope?: string;
  saleSignal?: string;
  saleCampaignId?: string;
  saleConsecutiveSeenCount?: number;
  saleContentHash?: string;
  saleDiscountPercent?: number | null;
  saleEvidence?: string;
  saleEvidenceHash?: string;
  saleFailureCount?: number;
  saleFingerprint?: string;
  saleLastCheckedAt?: string;
  saleMissCount?: number;
  saleObservedThisRun?: boolean;
  reopenedAt?: string | null;
  saleScanCount?: number;
  saleStatus?: "changed" | "ended" | "evergreen" | "new" | "ongoing" | "unknown";
  saleVerification?: "discovery-lead" | "retailer-page";
  firstSeenAt?: string;
  sourceId: VinylShopSource["id"] | string;
  sourceDiscountPercent?: number | null;
  sourceCurrency?: string | null;
  sourceCountry?: string | null;
  sourceDefaultDiscountThreshold?: number | null;
  sourceGroup?: string | null;
  sourceMinNetProfit?: number | null;
  sourceMinROI?: number | null;
  sourceName: string;
  sourceNoiseLevel?: string | null;
  sourceListingTitle?: string;
  sourceOriginalPrice?: number | null;
  sourceItemPrice?: number | null;
  sourceShippingPrice?: number | null;
  sourcePublishedAt?: string | null;
  sourcePriority?: number | null;
  sourceRetailType?: string | null;
  sourceSaleLikelihood?: string | null;
  sourceUrl: string;
  status?: ArbitrageDecision;
  soldEvidence?: ArbitrageSoldEvidence;
  soldUnits30Days?: number | null;
  soldUnits90Days?: number | null;
  soldUnits365Days?: number | null;
  soldUnits1095Days?: number | null;
  salesPerMonth?: number | null;
  sellerAccountType?: string | null;
  sellerFeedbackPercentage?: number | null;
  sellerFeedbackScore?: number | null;
  sellThroughRate?: number | null;
  shopifyVariantId?: number | string | null;
  shopifyVariantTitle?: string | null;
  sku?: string | null;
  activeSupplyMonths?: number | null;
  title: string;
  totalSoldCount?: number | null;
};

export type ArbitrageScoredFind = ArbitrageFind & {
  allInCost: number;
  cashReturnPer30Days: number | null;
  costLedger: ArbitrageCostLedger;
  decision: ArbitrageDecision;
  currencyConversionRequired?: boolean;
  estimatedDaysToSell: number | null;
  evaluationVersion: number;
  estimatedMargin: number | null;
  expectedNetProfit: number | null;
  gates: {
    activeEvidence: boolean;
    demand: boolean;
    economics: boolean;
    evidenceFreshness: boolean;
    matchConfidence: boolean;
    offerFreshness: boolean;
    purchaseOffer: boolean;
    soldEvidence: boolean;
    supply: boolean;
  };
  marginRatio: number | null;
  longTermSalesPerMonth: number | null;
  longTermSupplyMonths: number | null;
  priorityBand: ArbitragePriorityBand;
  priorityBreakdown: ArbitragePriorityBreakdown;
  priorityScore: number;
  profitPer30Days: number | null;
  reasonCodes: string[];
  recommendedMaxPurchasePrice: number | null;
  recommendedStrategy: ArbitrageStrategyId | null;
  reasons: string[];
  roiRatio: number | null;
  strategyOptions: ArbitrageStrategyOption[];
};

export type ArbitrageRunQuality = {
  blockedSourceCount: number;
  directCatalogCoverageCount: number;
  directCatalogCoverageRate: number;
  directProductiveRate: number;
  directProductiveSourceCount: number;
  directSalePageCoverageCount: number;
  directSalePageCoverageRate: number;
  directSourceCount: number;
  minimumDirectCatalogCoverageRate: number;
  minimumDirectProductiveRate: number;
  parserEmptySourceCount: number;
  publishable: boolean;
  reasons: string[];
  status: "blocked" | "degraded" | "healthy";
  targetDirectCatalogCoverageRate: number;
  targetDirectProductiveRate: number;
  targetDirectSalePageCoverageRate: number;
};

export type ArbitrageRunManifest = {
  arguments?: Record<string, boolean | number | string>;
  completedAt?: string;
  requestedSourceIds?: string[];
  scannedSourceCount?: number;
  scannerVersion?: string;
  sourceCatalogCount?: number;
  startedAt?: string;
};

export type ArbitrageImportPayload = {
  createdAt: string;
  finds: ArbitrageFind[];
  phase?: "final" | "scan" | string;
  publicationStatus?: "final" | "provisional" | string;
  runId?: string;
  runManifest?: ArbitrageRunManifest;
  runMode?: string;
  runQuality?: ArbitrageRunQuality;
  saleCampaignLedger?: unknown;
  saleEvents?: ArbitrageFind[];
  saleLifecycleSummary?: unknown;
  saleObservations?: ArbitrageFind[];
  schemaVersion?: number;
  source?: string;
  sourceReports?: Array<Record<string, unknown>>;
  summary?: Record<string, unknown>;
};
